var obj = Object.freeze({
	UNKNOWN_CONNECTION_IDENTIFIER: 0x02,
	HARDWARE_FAILURE: 0x03,
	AUTHENTICATION_FAILURE: 0x05,
	PIN_OR_KEY_MISSING: 0x06,
	MEMORY_CAPACITY_EXCEEDED: 0x07,
	CONNECTION_TIMEOUT: 0x08,
	CONNECTION_LIMIT_EXCEEDED: 0x09,
	CONNECTION_ALREADY_EXISTS: 0x0B,
	COMMAND_DISALLOWED: 0x0C,
	CONNECTION_REJECTED_DUE_TO_LIMITED_RESOURCES: 0x0D,
	CONNECTION_REJECTED_DUE_TO_SECURITY_REASONS: 0x0E,
	UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE: 0x11,
	INVALID_HCI_COMMAND_PARAMETERS: 0x12,
	REMOTE_USER_TERMINATED_CONNECTION: 0x13,
	REMOTE_DEVICE_TERMINATED_CONNECTION_DUE_TO_LOW_RESOURCES: 0x14,
	REMOTE_DEVICE_TERMINATED_CONNECTION_DUE_TO_POWER_OFF: 0x15,
	CONNECTION_TERMINATED_BY_LOCAL_HOST: 0x16,
	REPEATED_ATTEMPTS: 0x17,
	PAIRING_NOT_ALLOWED: 0x18,
	UNSUPPORTED_REMOTE_FEATURE: 0x1A,
	INVALID_LL_PARAMETERS: 0x1E,
	UNSPECIFIED_ERROR: 0x1F,
	UNSUPPORTED_LL_PARAMETER_VALUE: 0x20,
	LL_RESPONSE_TIMEOUT: 0x22,
	LL_PROCEDURE_COLLISION: 0x23,
	INSTANT_PASSED: 0x28,
	DIFFERENT_TRANSACTION_COLLISION: 0x2A,
	PARAMETER_OUT_OF_MANDATORY_RANGE: 0x30,
	CONTROLLER_BUSY: 0x3A,
	UNACCEPTABLE_CONNECTION_PARAMETERS: 0x3B,
	ADVERTISING_TIMEOUT: 0x3C,
	CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE: 0x3D,
	CONNECTION_FAILED_TO_BE_ESTABLISHED: 0x3E,
	LIMIT_REACHED: 0x43,
	OPERATION_CANCELLED_BY_HOST: 0x44,
	PACKET_TOO_LONG: 0x45,
	
	toString: function(v) {
		for (var key in obj) {
			if (obj.hasOwnProperty(key) && key != "toString" && obj[key] == v) {
				return key;
			}
		}
		return "(unknown)";
	}
});

module.exports = obj;
